title: "Loïc Morel - Pandul"
description: "Rédacteur Bitcoin"
author: "Loïc Morel"
lang: fr
timezone: Europe/Paris

# URL GitHub
url: "https://pandul.fr"
baseurl: ""

permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - post/

# Métadonnées SEO
logo: "/assets/img/social-card.png"
social:
  name: "Loïc Morel - Pandul"
  links:
    - "https://x.com/Loic_Pandul"
    - "https://github.com/LoicPandul"

# Collections par défaut
defaults:
  - scope: {path: ""} 
    values:
      layout: "default"
