title: "Loïc Morel - Pandul"
description: "Rédacteur Bitcoin"
author: "Loïc Morel"
lang: fr
timezone: Europe/Paris

# URL GitHub
url: "https://pandul.fr"
baseurl: ""

permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

include:
  - ".well-known"


# Métadonnées SEO
logo: "/assets/img/social-card.png"
social:
  name: "Loïc Morel - Pandul"
  links:
    - "https://x.com/Loic_Pandul"
    - "https://github.com/LoicPandul"

# Collections dictionnaire, categorie, lettre
collections:
  dictionnaire:
    output: true
    permalink: /dictionnaire/:slug/
  categorie:
    output: true
    permalink: /dictionnaire/categorie/:slug/
  lettre:
    output: true
    permalink: /dictionnaire/lettre/:slug/

# Collections par défaut
defaults:
  - scope: {path: ""}
    values:
      layout: "default"
  - scope:
      type: dictionnaire
    values:
      layout: "definition"
  - scope:
      type: categorie
    values:
      layout: "category"
  - scope:
      type: lettre
    values:
      layout: "letter"
